rly_file = "LeedsAndBradford.rly"
ttb_files = []
ssn_files = []
country_code = "GB"
name = ""
description = ""
display_name = "Leedsandbradford"
author = "Daniel Gill"
contributors = [ "Daniel-Gill",]
